# Generated by Django 3.2.3 on 2021-06-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='webshop_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='parent_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_mainoksia', to='api.company'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_of_mainoksia'),
        ),
    ]
