# Generated by Django 3.2.3 on 2021-06-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210605_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos'),
        ),
    ]
